# Generated by Django 4.1.3 on 2023-01-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('skill_title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTechnology',
            fields=[
                ('tech_title', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(default='Oferta pracy', max_length=100)),
                ('offer_description', models.CharField(default='Opis oferty pracy', max_length=250)),
                ('offer_post_time', models.DateTimeField(auto_now_add=True)),
                ('offer_skills', models.ManyToManyField(to='account.jobskill')),
                ('offer_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobtechnology')),
            ],
        ),
    ]
