# Generated by Django 4.1.3 on 2023-03-14 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('app_text', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('cv', models.BooleanField(default=False)),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=250)),
                ('message_sent_time', models.DateTimeField(auto_now_add=True)),
                ('message_read_time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_compensation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='filter',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
        migrations.AddField(
            model_name='filter',
            name='seniority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.seniority'),
        ),
        migrations.AddField(
            model_name='filter',
            name='skills',
            field=models.ManyToManyField(to='account.skill'),
        ),
        migrations.AddField(
            model_name='filter',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.technology'),
        ),
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.offer'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_seniority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.seniority'),
        ),
    ]
