# Generated by Django 4.1.3 on 2023-03-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
