# Generated by Django 4.1.3 on 2023-05-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_text',
            field=models.CharField(max_length=250, verbose_name='Application info'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='seniority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.seniority'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='account.skill'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.technology'),
        ),
    ]
