# Generated by Django 4.1.3 on 2023-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_application_app_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='skill_query',
            field=models.TextField(blank=True),
        ),
    ]
