# Generated by Django 4.1.3 on 2023-03-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_application_company_filter_location_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seniority',
            options={'verbose_name_plural': 'Seniorities'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_seniority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.seniority'),
        ),
    ]
