# Generated by Django 4.1.3 on 2023-05-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_filter_skill_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='/companies/2023/05/09/pobrane.png', upload_to='companies/%Y/%m/%d/'),
        ),
    ]
