# Generated by Django 4.1.3 on 2023-04-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_seniority_options_alter_offer_offer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_seniority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.seniority'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
