# Generated by Django 4.1.3 on 2023-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_joboffer_offer_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='offer_seniority',
            field=models.CharField(choices=[('0', 'Intern'), ('1', 'Junior'), ('2', 'Mid'), ('3', 'Senior')], default='1', max_length=6),
        ),
    ]
