# Generated by Django 4.1.3 on 2023-05-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_offer_offer_company_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
