# Generated by Django 4.1.3 on 2023-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_offer_offer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='companies/%Y/%m/%d/'),
        ),
    ]
