# Generated by Django 4.1.3 on 2023-05-23 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_company_logo_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_skills',
            field=models.ManyToManyField(blank=True, to='account.skill'),
        ),
    ]
